/**
 *author Aaron Barr
 * for an interview project
 * 
 */
import java.io.File;
import java.io.FileNotFoundException;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;


public class RewardsProgram {

    public static void main(String[] args) {
        // Gain one point for each dollar over $50, up to $100
        // Gain 2 point for every dollar after $100
        // Read in a transaction:  "Customer", "Date", "purchase amount" *one line*
        try{
        
            Scanner document = new Scanner(new File(args[0]));
            HashMap<String,Map<String,Integer>> customerPoints = new HashMap<>();
        
            while(document.hasNext()){
                String[] transaction = document.nextLine().split(" ");
                String customer = transaction[0];
                String date = transaction[1]; // MM-DD-YYYY
                String month = date.substring(0, 2);
                String purchase = transaction[2];
                int purchaseAsInt = Integer.parseInt(purchase);


            int points = findPoints(purchaseAsInt);
            
            //If you do NOT have the customer already, add them
            if(!customerPoints.containsKey(customer)){  
                customerPoints.put(customer, new HashMap<>());  
                customerPoints.get(customer).put(month, points);
            }
           
            //If you have the customer already
            else{
            
                //Check if you have the month already
                if(customerPoints.get(customer).containsKey(month)){
                    
                    //If yes, update the value
                    int oldValue = (int)customerPoints.get(customer).get(month);
                    points += oldValue;
                    customerPoints.get(customer).replace(month, points);
                }
                else{
                    //If not the add the month in
                    customerPoints.get(customer).put(month, points);
                }
            }
        }
        
            //Iterate through the map of customers
            for(Map.Entry<String, Map<String,Integer>> customerEntry : customerPoints.entrySet()){
                int pointSum = 0;
                System.out.println(customerEntry.getKey());

                //Iterate through the map of monthly point values and display them
                for(Map.Entry<String,Integer> entry : customerEntry.getValue().entrySet()){
                    System.out.println("Month: " + entry.getKey() +"  Monthly Points: " + entry.getValue());
                    pointSum += entry.getValue();
                }
                //Display the total points accrued
                System.out.println("Total points accrued: " + pointSum);
            }

        }
          catch(FileNotFoundException e){
              System.out.println("That file was not found.  Please check the pathname");
        }
    }
    
    //A method that takes in an amount of dollars and calculates the points generated by those dollars 
    static int findPoints(int dollars){
        int points =0;
        if(dollars > 100)
            points = (dollars - 100) * 2 + 50;
        
        if(dollars <= 100 && dollars >50)
            points = dollars - 50;
        
        return points;
    }
}
